update

diff --git a/build_fuzzer b/build_fuzzer
--- a/build_fuzzer
+++ b/build_fuzzer
@@ -34,7 +34,14 @@ if [ ! -f "Strategies/${fuzzer}"".v" ]; then
     exit 1
 fi
 
-qc_path=$OPAM_SWITCH_PREFIX"/lib/coq/user-contrib/QuickChick"
+qc_path="$(opam var coq-quickchick:share)"
+
+if [ ! -f "$qc_path/Stub.ml" ]; then
+    echo "Error: QuickChick fuzzer support files not found in $qc_path" >&2
+    echo "Did you install the local QuickChick port with opam?" >&2
+    exit 1
+fi
+
 
 # Build the fuzzer
 
@@ -51,15 +58,15 @@ if [ ! $just_compile ]; then
     cp $stub_path $extended_fuzzer_path &&
     echo $'\n\n(* -----(Stub Ends)----- *)\n\n' >> $extended_fuzzer_path &&
     ## 1.2. Add the fuzzer to the extended fuzzer
-    cat ${fuzzer}_path >> $extended_fuzzer_path &&
+    cat ${fuzzer_path} >> $extended_fuzzer_path &&
     ## 1.3. Create the extended mli file
     touch $extended_mli_path &&
     ocamlc -c $extended_mli_path
 
     # 2. Build the fuzzer
     ## 2.1. Make it tail recursive
-    $qc_path"/cmdprefix.pl" ${fuzzer}"_test_runner_ext.ml" &&
-    $qc_path"/cmdsuffix.pl" ${fuzzer}"_test_runner_ext.ml"
+    # $qc_path"/cmdprefix.pl" ${fuzzer}"_test_runner_ext.ml" &&
+    # $qc_path"/cmdsuffix.pl" ${fuzzer}"_test_runner_ext.ml"
 fi
 ## 2.2. Run ocaml compiler
 ocamlfind ocamlopt -ccopt -Wno-error=implicit-function-declaration -afl-instrument -linkpkg -package unix -package str -package coq-core.plugins.extraction -thread -rectypes -w a -o ${fuzzer}"_exec" ${fuzzer}"_test_runner_ext.ml" $qc_path"/SHM.c" &&
